# Generated by Django 6.0.4 on 2026-05-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("no_of_guests", models.IntegerField()),
                ("booking_date", models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name="menu",
            name="description",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="name",
        ),
        migrations.AddField(
            model_name="menu",
            name="inventory",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="menu",
            name="title",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
