# Generated by Django 6.0.4 on 2026-05-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0002_booking_remove_menu_description_remove_menu_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="menu",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
